go-python/gopy

_examples/hi/hi.go, _examples/hi/test.py, bind/bind.go, bind/gencpy.go, bind/gengo.go, bind/package.go, bind/printer.go, bind/printer_test.go, bind/types.go, bind/utils.go, bind/vars.go, gen.go, main_test.go
- rationalize cpython type strings
- generate cgo stub functions, calling structs methods
- generate (invalid) bodyless cpython functions for struct methods
fixes #3
fixes #4
=> refactor gencpy

_examples/hi/test.py, bind/gencpy.go, bind/gengo.go, main_test.go
This CL implements a ref-counting scheme for go values passed to the python
world.
Go values (actually, their unsafe.Pointer) are associated with a reference
counter as soon as they exit the Go world.
These values are also pinned inside a global map to prevent the GC from moving
them around.
Conversely, python objects wrapping Go values will decrease the reference
counter when the __del__ method is called.
Fixes #7
Change-Id: I9b6434d0933b7abe409ac130f3a8c0655c1f23a9
=> bind: support for cross-ref gc

_examples/maps/maps.go, bind/gencpy_type.go, bind/symtab.go, bind/types.go
Adding code so that the GO parser will now recognize maps in function declarations. No wrapper methods have been added to make them useable yet.
=> bind: starting support for maps in go

bind/gengo.go
I think this was a small omission.  `genFuncBody` generates calls to `cgopy_incref` for all of the return values that require reference counts, but `genMethodBody` was missing that logic.  This causes a panic with the message "cgopy: decref untracked object" for Go methods that return objects when those objects are eventually deleted.
=> Increment reference count for results in genMethodBody.

_examples/hi/hi.go, _examples/hi/test.py, bind/gencpy_func.go, main_test.go
I'm trying out hello worlds and all with Go and Go-Python integration and stumbled upon issue with functions, returning (string, error).
This example fails with SIGSEGV upon call:
```
func NoProblemmo() (string, error) {
return "No Problemmo!", nil
}
```
Please see commit for details, it's pretty straightforward.
=> Fixed bug with SIGSEGV if function returns (string, error)

_examples/wrapper/pywrapper/wrapper_code.go, bind/gengo.go, bind/utils.go, main_test.go
This CL adds a test to make sure we always correctly `gofmt` our code (actually, if `goimports` is available, we run it instead of `gofmt`)
=> Gofmt check

.travis.yml, bind/bind.go, bind/gencffi.go, bind/gencffi_cdef.go, bind/gencffi_func.go, cmd_bind.go, gen.go, main_test.go
* gopy/gen.go: Add a new "cffi" language switch
* gopy/cmd_bind.go: Reduce to using cmd copy command.
* gopy/bind/gencffi.go: Add a new cffiGen type, modeled after cpyGen.
* gopy/bind/gencffi_cdef.go: Expose CAPI generated by cgo for CFFI.
* gopy/bind/gencffi_func.go: Generate CFFI wrapped functions.
* gopy/gen.go: Generate a CFFI builder python file and a wrapping CFFI python file.
* goby/main_test.go: Add test case for CFFI with simple.go.
Fixes go-python/gopy#48, go-python/gopy#87
=> gopy,bind: add boilerplate code for cffi support

_examples/vars/test.py, bind/bind.go, bind/gencffi.go, bind/gencffi_cdef.go, bind/gencffi_func.go, cmd_bind.go, gen.go, main_test.go
- Remove the generating builder python script.
- Now, genCFFI interface is same as the genCpy.
- Support builtin-types Vars and Consts.
- Pass `empty.go`
- Pass `cgo.go`
- Pass `vars.go` + Add set vars test.
- Pass `consts.go`
Updates: go-python/gopy#102
=> bind, gencffi: Remove generating builders and support Vars and Consts.

_examples/pyerrors/pyerrors.go, _examples/pyerrors/test.py, bind/gencffi.go, bind/gencffi_cdef.go, bind/gencffi_func.go, bind/gengo.go, main_test.go
* Detect functions returning a Go error and make them pythonic (raising an Exception).
* Add tests for it.
Now it only supports 2 return values.
CPy2 and CFFI should support more return values.
Fixes: go-python/gopy#104
=> gencffi: Detect functions returning a Go error

cmd_bind.go
gopy: go-1.9 requires exactly one main package for c-shared libs
Fix: go-python/gopy#108
=> gopy: go-1.9 requires exactly one main package for c-shared libs

README.md
Very interested in the interoperability between Python and Go, so I came across this project thanks to the Gophers Slack channel 🙂 
Saw there was a small mistake in formatting a link in the README so figured I'd open this PR.
=> doc: Fix markdown syntax for license link

_examples/named/test.py, bind/doc.go, bind/gencffi.go, bind/gencffi_cdef.go, bind/gencffi_func.go, bind/gencffi_struct.go, bind/gencffi_type.go, main_test.go
* Pass 'named.go' test.
* Support to generate named type includes slice and array types.
* Add doc.go for bind package.
* Add comments.
* Support __iadd__ for Go slice types.
* Add a 'seq.go' test for the CFFI engine.
Fix: go-python/gopy#121
=> cffi: Support named type + Pass 'seq.go' test.

_examples/hi/test.py, bind/gencffi_cdef.go, bind/gencffi_struct.go, bind/gencffi_type.go, bind/symtab.go, main_test.go
* Pass hi.go
* Support unnamed types.
This PR should be reviewd after #120 is merged.
=> cffi: Support unnamed types and pass hi.go

_examples/hi/test.py, _examples/structs/test.py, main_test.go
This CL makes sure we are more or less ready for python3.
- import `__future__.print_function` so python2 can use the same
`print(foo, bar)` syntax than python3
- use the python3 syntax for catching exceptions
This CL makes sure we are using python2 for the tests.
Eventually, we'll have to test both.
=> Py2py3 syntax

bind/gencpy_struct.go, main_test.go
Before this CL we used to prepend the Go package name of a struct to the
python name of the corresponding python class:
```python
>>> import pkg
>>> f = pkg.Foo()
>>> f.bar
caught error: 'pkg.Foo' object has no attribute 'bar'
```
This CL drops 'pkg' to make the resulting string follow CPython
convention:
```python
>>> import pkg
>>> f = pkg.Foo()
>>> f.bar
caught error: 'Foo' object has no attribute 'bar'
```
Fixes go-python#gopy/119.
=> gopy,bind: drop package name out of tp_name

main_test.go, zsupport_go16_test.go, zsupport_test.go
This CL adds support for sub-tests for Go >= 1.7 and adds the needed
fallback code for Go < 1.7.
This allows to run sub-tests in parallel, where each sub-test tests a
backend (py2-cffi, py3-cffi, py3, ...).
=> gopy: add support for sub-tests

.travis.yml, main_test.go, zsupport_test.go
- There was a bug in test which didn't disable py2-cffi test backend
even if the cffi module wasn't present on the system. This was because py2
and py2-cffi were by default part of the enabled backends and were never disabled.
- We shouldn't have default enabled backends and should enable
only if support is present.
- The value for testBackends needs to be only a bool instead of an int.
- Also added some log messages.
=> test: Running go test without py2-cffi throws errors

_examples/lot/lot.go, _examples/lot/test.py, bind/gencffi_struct.go, main_test.go
This CL makes valid syntax for slices cases.
Updates go-python/gopy#156.
=> cffi: Fix invalid syntax for slices in generated Python

SUPPORT_MATRIX.md, _examples/rename/rename.go, _examples/rename/test.py, bind/gencffi_func.go, bind/gencpy.go, bind/gencpy_struct.go, bind/utils.go, bind/utils_test.go, main_test.go
We're porting a library to Go using Gopy and we need to keep the method and function names the same as in the old implementation.
Currently, only exported functions, starting with an uppercase character, can have a binding generated.
This PR adds a directive, which allows changing the name in the following way:
```
//python:name test
func Test() {
...
}
```
=> Add the ability to change method and function names

SUPPORT_MATRIX.md, _examples/sliceptr/sliceptr.go, _examples/sliceptr/test.py, bind/gencpy_type.go, bind/gengo.go, bind/symtab.go, bind/vars.go, main_test.go
Implement support for pointer-to-slice parameters for methods and functions:
Python:
```
import tst
s = tst.StrSlice()
tst.Fill(s)
print s
```
Go:
```
package tst
type StrSlice []string
func Fill(s *StrSlice) {
*s = StrSlice{"A", "B"}
}
```
This doesn't implement pointer support in general (as we didn't need it), but the fixes should make the implementation easier.
=> Support for pointer-to-slice parameters

bind/utils.go, bind/utils_test.go
Sorry, I messed up the identifier validation. Underscores should be allowed at any position.
=> gopy/bind: allow renamed Python identifiers to start with an underscore

SUPPORT_MATRIX.md, bind/gencffi.go, bind/gencffi_cdef.go, bind/gencffi_type.go, main_test.go
This PR makes the `sliceptr` example work with the CFFI backend.
Improves https://github.com/go-python/gopy/commit/5f71fa457cb119a5e2ddf38ee7c1f4a963f2b178 .
=> gopy/bind: support pointers-to-slices with the cffi backend

_examples/structs/test.py, bind/gencpy_struct.go, main_test.go
To mimic a SWIG library I'm porting, I'd like to inherit from GoPy-generated objects.
I believe that switching the flag should be everything that is necessary for this to work. GoPy objects do not serve as collections of Python objects, so handling GC is not needed and the lifecycle seems to be handled well enough so that no resources are leaked.
=> gopy/bind: enable subclassing of generated CPython objects

SUPPORT_MATRIX.md, _examples/cgo/test.py, _examples/empty/test.py, _examples/named/test.py, _examples/seqs/test.py, _examples/simple/test.py, _examples/structs/test.py, _examples/unicode/encoding.go, _examples/unicode/test.py, _examples/vars/test.py, bind/gencffi.go, bind/gencpy.go, main_test.go
This PR builds on https://github.com/go-python/gopy/pull/170.
Currently, Python 3 CFFI returns Unicode, but Python 2 backends do not.
In Python 2, both byte and Unicode strings inherit from basestring and are interchangeable for most purposes. Some code might break, as Python 2 tries to encode Unicode strings to PYTHONIOENCODING while doing IO, and the specific encoding might be unable to represent the characters present in the string. Programs which ignore encoding _and_ have the need to output fancy characters suffer.
CPython 2 docstrings as Unicode are not implemented by this PR, but I do not think this is an issue.
Making the tests portable is difficult -- only the test for Unicode needs to handle IO encoding seriously. In the others I just strip the potential `u` which `repr` uses to …
=> Pass Go strings to Python as Unicode objects

bind/utils.go, cmd_build.go
Currently, Gopy does not work easily on Windows.
While not automatically fixing that, this allows you to use environment variables to help Gopy find the include and lib dirs.
Also adds -Ofast flag when building Python extension module, in order to help performance a little bit.
Filepath.ToSlashes is also used for include and lib directories as it seems to be required.
The environment variables are:
GOPY_INCLUDE: The include directory where your Python headers are. For example: "C:\python38\include"
GOPY_LIBDIR: The folder where the Python development libraries are. Example: "C:\python38\libs".
GOPY_PYLIB: The name of the Python library to link against. It's what ever you put after the -l command if you manually compile extension modules using GCC. Example: "python37".
These are only used …
=> Added environment variable support

main_test.go
I noticed that gopy had to be in a GOPATH, pre modules, directory layout for the tests to work. This PR writes a dummy go.mod into the temp dirs created for the tests.
=> fix tests to work with go modules

bind/gen.go, bind/gen_func.go, bind/gen_map.go, bind/gen_slice.go, bind/gen_type.go, bind/gen_varconst.go, bind/package.go, bind/symbols.go, bind/types.go
Pointer is needed so that elements can be modified -- no other way to do this python-side, and generated code assumes pointer receivers.
This has been fully tested on my extensive codebase..
=> for slices with non-pointer struct element types, need to return pointer to element

README.md
When I tried to execute examples, I got same errors and spent time for the errors. The errors depend on the environment (python env, or LD_LIBRARY_PATH), but I recommend you to revise the document for ease of execution.
=> Fix comments, Examples in README.md

bind/gen.go
This fix removes the static import of `enum.Enum` that was added only to the exe preamble, and replaces it with a conditional import added to all generated packages, only if there is at least one enum to generate.
The conditional import improves python2 legacy support where `Enum` is an external dependency that must be present.
Depends on ~~#241~~ being merged for test refactors.
=> bind: ensure enum.Enum is imported in generated code as needed

README.md
I deleted the outdated references from the linked issue.
Should this be replaced with a more up-to-date communication method or is it fine to leave it as is?
Closes #263
=> Removed out-dated ref. to Google Groups. Replace with something else?

_examples/variadic/test.py, _examples/variadic/variadic.go, bind/gen_func.go, bind/symbols.go, bind/types.go, main_test.go
Adding support for variadic functions
=> Adding support for variadic functions.

cmd_build.go, main.go
Signed-off-by: Achal Shah <achals@gmail.com>
We need support for build tags when trying to link to a project that has a dependency on certain build flags (in our case, arrow).
=> feat: Add support for build tags

_examples/slices/slices.go, _examples/slices/test.py, bind/gen_slice.go
When a slice element is a `PyObject*` pybindgen needs to know the ownership details.
=> Fix - slice element is pyobject

bind/symbols.go
when conflicting symbols exceeds, the generated symbol name will have control character.
=> gen symbol name use index to avoid illegal symobl name

README.md
The cross-plaform example had changed the file name in https://github.com/dataploy-ai/labsdk/commit/b1a79b8b7422ad1e8d29f510ff5e975696ffbfde
=> fix broken link on readme

cmd_build.go, cmd_exe.go, cmd_gen.go, cmd_pkg.go, gen.go
If `buildFirst` flag is set when loading packages, makes sure that the build flags are imported correctly to prevent intermediate errors like these: 
Issue is resolved later when package is actually built but we're missing build tags beforehand.
=> fix: Add build tags to loadPackage

README.md
The project linked to as an example had moved, I tracked it down through the author of the original issue that added the links.
=> Fix dead links to setup.py example in readme

bind/gen.go
Command `pkg` creates a mix of absolute and relative imports that make using the Python package impossible. See #309.
Handle imports for command `pkg` the same as `build` and `exe`.
For the default `PkgPrefix` (`.`), all imports now look like this:
```python
from . import xxx
```
Not sure why it was implemented differently for `pkg` compared to `build` and `exe`, so my approach may not be valid. However, it could also be a leftover bug from #245, #301 and #302.
Fixes #309
=> Fix: mixed absolute and relative imports

pkgsetup.go
Without this change, [cibuildwheel](https://github.com/pypa/cibuildwheel) cannot build a correct wheel from the generated project. The problem is that the native lib is added by `MANIFEST.in` and `python3 -m pip wheel` ignores it and thinks that the package is pure Python. Therefore it builds a pure wheel and the packaging pipeline crashes.
=> Enforce the extension module in setup.py

bind/gen_slice.go, main_test.go
Previously, it was not possible to iterate using the `for ... in ...` command in Python as shown below:
```python
from hltvsdk import operations
matches = operations.GetMatches()
for m in matches:
print(m.Team1)
```
The code above resulted in the following error:
```
Traceback (most recent call last):
File "/home/richecr/open_source/hltvgo/test.py", line 6, in <module>
print(m.Team1)
^^^^
AttributeError: 'int' object has no attribute 'Team1'
```
My fix addresses this issue. The solution essentially involved replicating the code generation as performed in the `__getitem__` method.
=> fix __next__ function

bind/utils.go
On Windows, python include folder may contain upper cases, here's an example generate the wrong LDFLAGS with gopy v0.4.7
```go
#cgo CFLAGS: -IC:/Users/test/miniconda3/envs/test/Include -Wno-error -Wno-implicit-function-declaration -Wno-int-conversion
#cgo LDFLAGS: -LC:/Users/test/miniconda3/envs/test/Include -lpython310
```
after the fix, it can works well on my environment
```go
#cgo CFLAGS: -IC:/Users/test/miniconda3/envs/test/Include -Wno-error -Wno-implicit-function-declaration -Wno-int-conversion
#cgo LDFLAGS: -LC:/Users/test/miniconda3/envs/test/libs -lpython310
```
Here're the console logs
```bash
--- Processing package: test/pkg/py ---
no LibDir -- copy from IncDir: C:/Users/test/miniconda3/envs/test/libs
```
fix #325
=> bind: fixed LDFLAGS on windows if python include path contains capital letters

bind/gen_map.go
This patch fixes a `panic` I was encountering when using a map whose value was a non-value-type like another Map, Struct, Slice, etc.
Related:
- #346 
- #329 
- [Commit ](https://github.com/richecr/gopy/commit/92d159f53618f6df6857069e49109b16058e1f66) by @richecr that fixed a similar issue for slices
This fix makes `gopy` useable for me but I have not added new tests (yet)
=> Fix `handleFromPtr` missing Reference in Maps

SUPPORT_MATRIX.md, _examples/gobytes/gobytes.go, _examples/gobytes/test.py, bind/gen_slice.go, main_test.go
This aims to solve both #323 and #328 by supplying efficient methods to copy Python `bytes` into Go `[]byte` slices and vice versa.
One question I have is whether the `Slice_byte` Python constructor should check if the first argument is of type `bytes`, and if so use the optimized method?
=> Efficient copies of bytes

bind/package.go
Fix this panic:
```
panic: interface conversion: types.Type is *types.Signature, not *types.Named
goroutine 1 [running]:
github.com/go-python/gopy/bind.(*Package).process(0xc01d5ee800)
/home/hugo/k/gopy/bind/package.go:340 +0x2078
github.com/go-python/gopy/bind.NewPackage(0xc009d2e720, 0xc00b228120)
/home/hugo/k/gopy/bind/package.go:68 +0x27c
main.parsePackage(0xc0203ec180)
/home/hugo/k/gopy/gen.go:159 +0x276
main.buildPkgRecurse({0xc0000ce640, 0x20}, {0xc0005d1ce0, 0x26}, {0x7ffd641ad938, 0x1b}, 0xc00d08bc68, {0x0, 0x0})
/home/hugo/k/gopy/cmd_pkg.go:162 +0x2b6
main.buildPkgRecurse({0xc0000ce640, 0x20}, {0xc01173e280, 0x20}, {0x7ffd641ad938, 0x1b}, 0xc00d08bc68, {0x0, 0x0})
/home/hugo/k/gopy/cmd_pkg.go:174 +0x428
main.buildPkgRecurse({0xc0000ce640, 0x20}, {0x7ffd641ad938, 0x1b}, …
```
=> fix panic when packaged go code relies on structural typing

_examples/slices/slices.go, _examples/slices/test.py, bind/gen_slice.go, main_test.go
Fixes #346 
NOTE: The variadic test was failing for me before adding this test:
<details>
<summary>Click me</summary>
```
run cmd: [build -vm=python3 -output=/tmp/gopy-3250023487 -package-prefix  ./_examples/variadic]
go build -v ./_examples/variadic
--- Processing package: github.com/go-python/gopy/_examples/variadic ---
--- building package ---
gopy.test -test.paniconexit0 -test.timeout=10m0s
goimports -w variadic.go
go build -mod=mod -buildmode=c-shared -o variadic_go.so .
/home/evan/miniconda3/bin/python3 build.py
CGO_CFLAGS="-I/home/evan/miniconda3/include/python3.10" -fPIC -Ofast
CGO_LDFLAGS="-L/home/evan/miniconda3/lib" "-lpython3.10" -lcrypt -lpthread -ldl -lutil -lm -lm
go build -mod=mod -buildmode=c-shared -o _variadic.cpython-310-x86_64-linux-gnu.so .
running python3 test.py …
```
=> Adds missing pointer reference for slices along with test

bind/gen_slice.go
修复 python 3.12 版本无法编译的Bug
原生成后代码:
```golang
func Slice_byte_to_bytes(handle CGoHandle) *C.PyObject {
s := deptrFromHandle_Slice_byte(handle)
ptr := unsafe.Pointer(&s[0])
size := len(s)
return C.PyBytes_FromStringAndSize((*C.char)(ptr), C.long(size))
}
```
替换此例子中的C.long为C.longlong
实测修复后gopy build 正常
=> Replacement c.long(size) for c.longlong(size)

cmd_build.go
Underlying `go build` commands can pass custom `CFLAGS` and `LDFLAGS` to CGO invocations, which GoPy uses in order to pass some of its own command-line arguments to builds.
However, there are cases where additional, build-specific parameters may need to be used (e.g. in the case where we're linking against a static library which itself links to other dynamic libraries, which aren't set as options in the packages themselves); this commit respects any existing uses of the `CGO_CFLAGS` and `CGO_LDFLAGS` environment variables, and appends their values to ones used internally by GoPy if needed.
My own, specific use-case here is using GoPy in [`slidge-whatsapp`](https://git.sr.ht/~nicoco/slidge-whatsapp), and using [`go-fitz`](https://github.com/gen2brain/go-fitz), which links against …
=> build: Append existing CFLAGS and LDFLAGS for CGO

cmd_build.go
Fix deprecation error in clang 
```
clang: error: argument '-Ofast' is deprecated; use '-O3 -ffast-math' for the same behavior, or '-O3' to enable only conforming optimizations [-Werror,-Wdeprecated-ofast]
```
Closes #371
=> Migrate clang call from deprecated '-Ofast' to '-O3 -ffast-math'

CONTRIBUTE.md
replaces mailing list ( go-python@googlegroups.com ), with links to GitHub discussions
=> link to GitHub discussions area
